# 
# Hifi Superstar Discord Bot
# Copyright (c) 2021 - 2022 by Philip Butkiewicz and contributors <https://github.com/philipbutkiewicz>
#

MUSIC_PLAY = 'MUSIC_PLAY'
MUSIC_STOP = 'MUSIC_STOP'
MUSIC_SKIP = 'MUSIC_SKIP'
MUSIC_SET_VOLUME = 'MUSIC_SET_VOLUME'
MUSIC_SET_REPEAT = 'MUSIC_SET_REPEAT'
MUSIC_QUEUE = 'MUSIC_QUEUE'
MUSIC_TOP_TRACKS = 'MUSIC_TOP_TRACKS'
MUSIC_PLAYLIST_SAVE = 'MUSIC_PLAYLIST_SAVE'
MUSIC_PLAYLIST_DELETE = 'MUSIC_PLAYLIST_DELETE'
MUSIC_PLAYLIST_LIST = 'MUSIC_PLAYLIST_LIST'
MUSIC_PLAYLIST_QUEUE = 'MUSIC_PLAYLIST_QUEUE'
MUSIC_SHOW_CONFIG = 'MUSIC_SHOW_CONFIG'
TTS_SPEAK = 'TTS_SPEAK'
TTS_LIST_VOICES = 'TTS_LIST_VOICES'
IMAGE_SEARCH = 'IMAGE_SEARCH'

